/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sa.csmarc.dashboard.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import sa.csmarc.dashboard.model.transactions;
import sa.csmarc.dashboard.service.transactionsLocalServiceUtil;

/**
 * The extended model base implementation for the transactions service. Represents a row in the &quot;dashboard_transactions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link transactionsImpl}.
 * </p>
 *
 * @author Salem
 * @see transactionsImpl
 * @see sa.csmarc.dashboard.model.transactions
 * @generated
 */
public abstract class transactionsBaseImpl extends transactionsModelImpl
	implements transactions {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a transactions model instance should use the {@link transactions} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			transactionsLocalServiceUtil.addtransactions(this);
		}
		else {
			transactionsLocalServiceUtil.updatetransactions(this);
		}
	}
}